name: ðŸš¦ Run Cypress Tests

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Setup Node.js Environment
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Step 3: Install Dependencies
      - name: Install dependencies
        run: npm ci

      # Step 4: Verify Cypress Installation
      - name: Verify Cypress cache
        run: npx cypress verify

      # Step 5: Clean old reports (avoid corrupted JSON merge)
      - name: Clean old reports
        run: rm -rf cypress/reports && mkdir -p cypress/reports

      # Step 6: Run Cypress Tests with Mochawesome reporter
      - name: Run Cypress tests with Mochawesome
        run: npm run cypress:run
      # Cleanup Step: Clean npm cache to reduce disk usage
      - name: Clean npm cache
        run: npm cache clean --force


      # Step 7: Merge and Generate HTML Report
      - name: Merge and Generate Mochawesome HTML Report
        if: always()
        run: |
          npm run merge:reports
          npm run generate:html

      # Step 8: Upload Cypress Artifacts (Screenshots, Videos, Reports)
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-results
          path: |
            cypress/screenshots
            cypress/videos
            cypress/reports

      # Step 9: Upload Final HTML Report (for easy access)
      - name: Upload HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-html-report
          path: cypress/reports/html/
